DROP TABLE `account`;--> statement-breakpoint
DROP TABLE `bookings`;--> statement-breakpoint
DROP TABLE `customer_profiles`;--> statement-breakpoint
DROP TABLE `customer_settings`;--> statement-breakpoint
DROP TABLE `customer_wallet_transactions`;--> statement-breakpoint
DROP TABLE `customer_wallets`;--> statement-breakpoint
DROP TABLE `driver_reviews`;--> statement-breakpoint
DROP TABLE `driver_rides`;--> statement-breakpoint
DROP TABLE `driver_settings`;--> statement-breakpoint
DROP TABLE `driver_wallets`;--> statement-breakpoint
DROP TABLE `drivers`;--> statement-breakpoint
DROP TABLE `drivers_new`;--> statement-breakpoint
DROP TABLE `reviews`;--> statement-breakpoint
DROP TABLE `session`;--> statement-breakpoint
DROP TABLE `user`;--> statement-breakpoint
DROP TABLE `vehicles`;--> statement-breakpoint
DROP TABLE `verification`;--> statement-breakpoint
DROP TABLE `wallet_transactions`;--> statement-breakpoint
DROP TABLE `wallet_transactions_new`;