import { db } from '@/db';
import { customerWalletTransactions } from '@/db/schema';

async function main() {
    const sampleTransactions = [
        {
            userId: 'TEu8VB1NnDXbBdv22B99eFal54MN0WBb',
            walletId: 1,
            type: 'add_money',
            amount: 1000,
            balanceBefore: 0,
            balanceAfter: 1000,
            description: 'Added money via UPI',
            referenceNumber: 'CWTXN1706774400ABC123',
            bookingId: null,
            paymentMethod: 'upi',
            status: 'completed',
            createdAt: new Date('2024-02-01T10:30:00').toISOString(),
        },
        {
            userId: 'TEu8VB1NnDXbBdv22B99eFal54MN0WBb',
            walletId: 1,
            type: 'ride_payment',
            amount: 250,
            balanceBefore: 1000,
            balanceAfter: 750,
            description: 'Ride payment for booking #BM1001',
            referenceNumber: 'CWTXN1707120000DEF456',
            bookingId: 1001,
            paymentMethod: 'wallet',
            status: 'completed',
            createdAt: new Date('2024-02-15T14:20:00').toISOString(),
        },
        {
            userId: 'TEu8VB1NnDXbBdv22B99eFal54MN0WBb',
            walletId: 1,
            type: 'add_money',
            amount: 500,
            balanceBefore: 750,
            balanceAfter: 1250,
            description: 'Added money via credit card',
            referenceNumber: 'CWTXN1709280000GHI789',
            bookingId: null,
            paymentMethod: 'card',
            status: 'completed',
            createdAt: new Date('2024-03-01T09:15:00').toISOString(),
        },
        {
            userId: 'TEu8VB1NnDXbBdv22B99eFal54MN0WBb',
            walletId: 1,
            type: 'ride_payment',
            amount: 180,
            balanceBefore: 1250,
            balanceAfter: 1070,
            description: 'Ride payment for booking #BM1002',
            referenceNumber: 'CWTXN1710576000JKL012',
            bookingId: 1002,
            paymentMethod: 'wallet',
            status: 'completed',
            createdAt: new Date('2024-03-16T16:45:00').toISOString(),
        },
        {
            userId: 'TEu8VB1NnDXbBdv22B99eFal54MN0WBb',
            walletId: 1,
            type: 'bonus',
            amount: 50,
            balanceBefore: 1070,
            balanceAfter: 1120,
            description: 'Referral bonus',
            referenceNumber: 'CWTXN1712160000MNO345',
            bookingId: null,
            paymentMethod: null,
            status: 'completed',
            createdAt: new Date('2024-04-03T11:00:00').toISOString(),
        },
        {
            userId: 'TEu8VB1NnDXbBdv22B99eFal54MN0WBb',
            walletId: 1,
            type: 'ride_payment',
            amount: 320,
            balanceBefore: 1120,
            balanceAfter: 800,
            description: 'Ride payment for booking #BM1003',
            referenceNumber: 'CWTXN1714752000PQR678',
            bookingId: 1003,
            paymentMethod: 'wallet',
            status: 'completed',
            createdAt: new Date('2024-05-03T13:30:00').toISOString(),
        },
        {
            userId: 'TEu8VB1NnDXbBdv22B99eFal54MN0WBb',
            walletId: 1,
            type: 'add_money',
            amount: 500,
            balanceBefore: 800,
            balanceAfter: 1300,
            description: 'Added money via net banking',
            referenceNumber: 'CWTXN1717430400STU901',
            bookingId: null,
            paymentMethod: 'netbanking',
            status: 'completed',
            createdAt: new Date('2024-06-03T18:00:00').toISOString(),
        },
        {
            userId: 'TEu8VB1NnDXbBdv22B99eFal54MN0WBb',
            walletId: 1,
            type: 'ride_payment',
            amount: 450,
            balanceBefore: 1300,
            balanceAfter: 850,
            description: 'Ride payment for booking #BM1004',
            referenceNumber: 'CWTXN1719936000VWX234',
            bookingId: 1004,
            paymentMethod: 'wallet',
            status: 'completed',
            createdAt: new Date('2024-07-02T15:20:00').toISOString(),
        },
        {
            userId: 'TEu8VB1NnDXbBdv22B99eFal54MN0WBb',
            walletId: 1,
            type: 'ride_payment',
            amount: 200,
            balanceBefore: 850,
            balanceAfter: 650,
            description: 'Ride payment for booking #BM1005',
            referenceNumber: 'CWTXN1722528000YZA567',
            bookingId: 1005,
            paymentMethod: 'wallet',
            status: 'completed',
            createdAt: new Date('2024-08-01T10:45:00').toISOString(),
        },
        {
            userId: 'TEu8VB1NnDXbBdv22B99eFal54MN0WBb',
            walletId: 1,
            type: 'refund',
            amount: 200,
            balanceBefore: 650,
            balanceAfter: 850,
            description: 'Refund for cancelled ride #BM1005',
            referenceNumber: 'CWTXN1722614400BCD890',
            bookingId: 1005,
            paymentMethod: null,
            status: 'completed',
            createdAt: new Date('2024-08-02T10:00:00').toISOString(),
        },
        {
            userId: 'TEu8VB1NnDXbBdv22B99eFal54MN0WBb',
            walletId: 1,
            type: 'ride_payment',
            amount: 150,
            balanceBefore: 850,
            balanceAfter: 700,
            description: 'Ride payment for booking #BM1006',
            referenceNumber: 'CWTXN1725292800EFG123',
            bookingId: 1006,
            paymentMethod: 'wallet',
            status: 'completed',
            createdAt: new Date('2024-09-02T12:00:00').toISOString(),
        },
        {
            userId: 'TEu8VB1NnDXbBdv22B99eFal54MN0WBb',
            walletId: 1,
            type: 'bonus',
            amount: 100,
            balanceBefore: 700,
            balanceAfter: 800,
            description: 'First ride bonus',
            referenceNumber: 'CWTXN1727884800HIJ456',
            bookingId: null,
            paymentMethod: null,
            status: 'completed',
            createdAt: new Date('2024-10-02T14:30:00').toISOString(),
        },
        {
            userId: 'TEu8VB1NnDXbBdv22B99eFal54MN0WBb',
            walletId: 1,
            type: 'ride_payment',
            amount: 300,
            balanceBefore: 800,
            balanceAfter: 500,
            description: 'Ride payment for booking #BM1007',
            referenceNumber: 'CWTXN1730563200KLM789',
            bookingId: 1007,
            paymentMethod: 'wallet',
            status: 'completed',
            createdAt: new Date('2024-11-02T16:00:00').toISOString(),
        },
        {
            userId: 'TEu8VB1NnDXbBdv22B99eFal54MN0WBb',
            walletId: 1,
            type: 'ride_payment',
            amount: 250,
            balanceBefore: 500,
            balanceAfter: 250,
            description: 'Ride payment for booking #BM1008',
            referenceNumber: 'CWTXN1733241600NOP012',
            bookingId: 1008,
            paymentMethod: 'wallet',
            status: 'completed',
            createdAt: new Date('2024-12-03T11:30:00').toISOString(),
        },
        {
            userId: 'TEu8VB1NnDXbBdv22B99eFal54MN0WBb',
            walletId: 1,
            type: 'add_money',
            amount: 250,
            balanceBefore: 250,
            balanceAfter: 500,
            description: 'Added money via UPI',
            referenceNumber: 'CWTXN1734523200QRS345',
            bookingId: null,
            paymentMethod: 'upi',
            status: 'completed',
            createdAt: new Date('2024-12-18T15:00:00').toISOString(),
        },
    ];

    await db.insert(customerWalletTransactions).values(sampleTransactions);
    
    console.log('✅ Customer wallet transactions seeder completed successfully');
}

main().catch((error) => {
    console.error('❌ Seeder failed:', error);
});