import { db } from '@/db';
import { vehicles } from '@/db/schema';

async function main() {
    const sampleVehicles = [
        {
            driverId: 1,
            type: 'government-bus',
            number: 'MH-01-AB-1234',
            model: 'Tata Starbus',
            capacity: 48,
            image: '/uploads/vehicles/bus_001.jpg',
            status: 'available',
            locationLat: '19.0760',
            locationLng: '72.8777',
            currentRoute: 'Mumbai-Pune',
            createdAt: new Date('2024-03-10'),
            updatedAt: new Date('2024-12-20'),
        },
        {
            driverId: 2,
            type: 'private-bus',
            number: 'DL-10-XY-5678',
            model: 'Ashok Leyland Viking',
            capacity: 45,
            image: '/uploads/vehicles/bus_002.jpg',
            status: 'available',
            locationLat: '28.7041',
            locationLng: '77.1025',
            currentRoute: 'Delhi-Agra',
            createdAt: new Date('2024-04-15'),
            updatedAt: new Date('2024-12-21'),
        },
        {
            driverId: 3,
            type: 'chartered-bus',
            number: 'KA-03-CD-9012',
            model: 'Volvo B9R',
            capacity: 55,
            image: '/uploads/vehicles/bus_003.jpg',
            status: 'booked',
            locationLat: '12.9716',
            locationLng: '77.5946',
            currentRoute: 'Bangalore-Mysore',
            createdAt: new Date('2024-05-20'),
            updatedAt: new Date('2024-12-22'),
        },
        {
            driverId: 4,
            type: 'government-bus',
            number: 'TN-09-EF-3456',
            model: 'BharatBenz',
            capacity: 42,
            image: '/uploads/vehicles/bus_004.jpg',
            status: 'available',
            locationLat: '13.0827',
            locationLng: '80.2707',
            currentRoute: 'Chennai-Pondicherry',
            createdAt: new Date('2024-06-10'),
            updatedAt: new Date('2024-12-19'),
        },
        {
            driverId: 5,
            type: 'private-bus',
            number: 'GJ-01-GH-7890',
            model: 'Tata Starbus Ultra',
            capacity: 50,
            image: '/uploads/vehicles/bus_005.jpg',
            status: 'maintenance',
            locationLat: '23.0225',
            locationLng: '72.5714',
            currentRoute: null,
            createdAt: new Date('2024-07-05'),
            updatedAt: new Date('2024-12-23'),
        },
        {
            driverId: 6,
            type: 'chartered-bus',
            number: 'RJ-14-IJ-2345',
            model: 'Ashok Leyland 2516',
            capacity: 40,
            image: '/uploads/vehicles/bus_006.jpg',
            status: 'available',
            locationLat: '26.9124',
            locationLng: '75.7873',
            currentRoute: 'Jaipur-Udaipur',
            createdAt: new Date('2024-08-12'),
            updatedAt: new Date('2024-12-21'),
        },
        {
            driverId: 7,
            type: 'government-bus',
            number: 'WB-06-KL-6789',
            model: 'Tata LPO 1512',
            capacity: 38,
            image: '/uploads/vehicles/bus_007.jpg',
            status: 'available',
            locationLat: '22.5726',
            locationLng: '88.3639',
            currentRoute: 'Kolkata-Siliguri',
            createdAt: new Date('2024-09-18'),
            updatedAt: new Date('2024-12-20'),
        },
        {
            driverId: 8,
            type: 'private-bus',
            number: 'AP-39-MN-0123',
            model: 'Volvo 9400',
            capacity: 52,
            image: '/uploads/vehicles/bus_008.jpg',
            status: 'booked',
            locationLat: '17.3850',
            locationLng: '78.4867',
            currentRoute: 'Hyderabad-Vijayawada',
            createdAt: new Date('2024-10-25'),
            updatedAt: new Date('2024-12-22'),
        },
        {
            driverId: 1,
            type: 'chartered-bus',
            number: 'MH-12-OP-4567',
            model: 'Scania Metrolink',
            capacity: 49,
            image: '/uploads/vehicles/bus_009.jpg',
            status: 'available',
            locationLat: '18.5204',
            locationLng: '73.8567',
            currentRoute: 'Pune-Mumbai',
            createdAt: new Date('2024-11-08'),
            updatedAt: new Date('2024-12-23'),
        },
        {
            driverId: 2,
            type: 'government-bus',
            number: 'UP-16-QR-8901',
            model: 'Ashok Leyland Vestibule',
            capacity: 35,
            image: '/uploads/vehicles/bus_010.jpg',
            status: 'available',
            locationLat: '25.3176',
            locationLng: '82.9739',
            currentRoute: 'Varanasi-Lucknow',
            createdAt: new Date('2024-11-22'),
            updatedAt: new Date('2024-12-21'),
        },
    ];

    await db.insert(vehicles).values(sampleVehicles);
    
    console.log('✅ Vehicles seeder completed successfully');
}

main().catch((error) => {
    console.error('❌ Seeder failed:', error);
});