import { db } from '@/db';
import { vehicles } from '@/db/schema';

async function main() {
    const sampleVehicles = [
        {
            vehicleNumber: 'MH-01-AB-1234',
            vehicleType: 'government-bus',
            capacity: 48,
            driverId: 'DRV001',
            status: 'active',
            currentRoute: 'Mumbai-Pune',
            locationLat: 19.0760,
            locationLng: 72.8777,
            createdAt: new Date('2024-01-15').toISOString(),
            updatedAt: new Date('2024-12-20').toISOString(),
        },
        {
            vehicleNumber: 'DL-10-XY-5678',
            vehicleType: 'government-bus',
            capacity: 50,
            driverId: 'DRV002',
            status: 'active',
            currentRoute: 'Delhi-Agra',
            locationLat: 28.7041,
            locationLng: 77.1025,
            createdAt: new Date('2024-02-10').toISOString(),
            updatedAt: new Date('2024-12-19').toISOString(),
        },
        {
            vehicleNumber: 'KA-03-CD-9012',
            vehicleType: 'government-bus',
            capacity: 45,
            driverId: null,
            status: 'inactive',
            currentRoute: null,
            locationLat: 12.9716,
            locationLng: 77.5946,
            createdAt: new Date('2024-03-05').toISOString(),
            updatedAt: new Date('2024-12-18').toISOString(),
        },
        {
            vehicleNumber: 'GJ-06-EF-3456',
            vehicleType: 'government-bus',
            capacity: 47,
            driverId: 'DRV003',
            status: 'active',
            currentRoute: 'Ahmedabad-Vadodara',
            locationLat: 23.0225,
            locationLng: 72.5714,
            createdAt: new Date('2024-04-20').toISOString(),
            updatedAt: new Date('2024-12-21').toISOString(),
        },
        {
            vehicleNumber: 'TN-09-GH-7890',
            vehicleType: 'private-bus',
            capacity: 42,
            driverId: 'DRV004',
            status: 'active',
            currentRoute: 'Chennai-Bangalore',
            locationLat: 13.0827,
            locationLng: 80.2707,
            createdAt: new Date('2024-05-12').toISOString(),
            updatedAt: new Date('2024-12-20').toISOString(),
        },
        {
            vehicleNumber: 'RJ-14-IJ-2345',
            vehicleType: 'private-bus',
            capacity: 44,
            driverId: 'DRV005',
            status: 'active',
            currentRoute: 'Jaipur-Udaipur',
            locationLat: 26.9124,
            locationLng: 75.7873,
            createdAt: new Date('2024-06-18').toISOString(),
            updatedAt: new Date('2024-12-19').toISOString(),
        },
        {
            vehicleNumber: 'UP-16-KL-6789',
            vehicleType: 'private-bus',
            capacity: 40,
            driverId: null,
            status: 'maintenance',
            currentRoute: null,
            locationLat: 25.4358,
            locationLng: 81.8463,
            createdAt: new Date('2024-07-25').toISOString(),
            updatedAt: new Date('2024-12-17').toISOString(),
        },
        {
            vehicleNumber: 'WB-19-MN-1357',
            vehicleType: 'chartered-bus',
            capacity: 52,
            driverId: 'DRV006',
            status: 'active',
            currentRoute: 'Kolkata-Darjeeling',
            locationLat: 22.5726,
            locationLng: 88.3639,
            createdAt: new Date('2024-08-08').toISOString(),
            updatedAt: new Date('2024-12-21').toISOString(),
        },
        {
            vehicleNumber: 'HR-26-OP-2468',
            vehicleType: 'chartered-bus',
            capacity: 55,
            driverId: 'DRV007',
            status: 'active',
            currentRoute: 'Chandigarh-Shimla',
            locationLat: 30.7333,
            locationLng: 76.7794,
            createdAt: new Date('2024-09-14').toISOString(),
            updatedAt: new Date('2024-12-20').toISOString(),
        },
        {
            vehicleNumber: 'AP-39-QR-8024',
            vehicleType: 'e-rickshaw',
            capacity: 6,
            driverId: 'DRV008',
            status: 'inactive',
            currentRoute: null,
            locationLat: 17.3850,
            locationLng: 78.4867,
            createdAt: new Date('2024-11-05').toISOString(),
            updatedAt: new Date('2024-12-15').toISOString(),
        },
    ];

    await db.insert(vehicles).values(sampleVehicles);
    
    console.log('✅ Vehicles seeder completed successfully');
}

main().catch((error) => {
    console.error('❌ Seeder failed:', error);
});