import { db } from '@/db';
import { walletTransactions } from '@/db/schema';

async function main() {
    const sampleTransactions = [
        // Driver 1 (driverId: 1, walletId: 1) - Starting balance: 0
        {
            driverId: 1,
            walletId: 1,
            type: 'credit',
            amount: 2000.00,
            balanceAfter: 2000.00,
            description: 'Added money via UPI',
            referenceNumber: 'TXN2024111500001',
            rideId: null,
            status: 'completed',
            createdAt: new Date('2024-11-15T10:30:00').toISOString(),
        },
        {
            driverId: 1,
            walletId: 1,
            type: 'ride_earning',
            amount: 450.00,
            balanceAfter: 2450.00,
            description: 'Ride earning from completed trip',
            referenceNumber: 'RDE2024120100001',
            rideId: 1,
            status: 'completed',
            createdAt: new Date('2024-12-01T14:20:00').toISOString(),
        },
        {
            driverId: 1,
            walletId: 1,
            type: 'ride_earning',
            amount: 320.00,
            balanceAfter: 2770.00,
            description: 'Ride earning from completed trip',
            referenceNumber: 'RDE2024120300001',
            rideId: 2,
            status: 'completed',
            createdAt: new Date('2024-12-03T09:15:00').toISOString(),
        },
        {
            driverId: 1,
            walletId: 1,
            type: 'credit',
            amount: 1500.00,
            balanceAfter: 4270.00,
            description: 'Added money via card',
            referenceNumber: 'TXN2024120400001',
            rideId: null,
            status: 'completed',
            createdAt: new Date('2024-12-04T16:45:00').toISOString(),
        },
        {
            driverId: 1,
            walletId: 1,
            type: 'ride_earning',
            amount: 580.00,
            balanceAfter: 4850.00,
            description: 'Ride earning from completed trip',
            referenceNumber: 'RDE2024120500001',
            rideId: 3,
            status: 'completed',
            createdAt: new Date('2024-12-05T11:30:00').toISOString(),
        },
        {
            driverId: 1,
            walletId: 1,
            type: 'withdrawal',
            amount: 3500.00,
            balanceAfter: 1350.00,
            description: 'Withdrawn to bank account',
            referenceNumber: 'WTH2024120600001',
            rideId: null,
            status: 'completed',
            createdAt: new Date('2024-12-06T15:00:00').toISOString(),
        },
        {
            driverId: 1,
            walletId: 1,
            type: 'ride_earning',
            amount: 390.00,
            balanceAfter: 1740.00,
            description: 'Ride earning from completed trip',
            referenceNumber: 'RDE2024120800001',
            rideId: 4,
            status: 'completed',
            createdAt: new Date('2024-12-08T13:25:00').toISOString(),
        },
        {
            driverId: 1,
            walletId: 1,
            type: 'ride_earning',
            amount: 410.00,
            balanceAfter: 2150.00,
            description: 'Ride earning from completed trip',
            referenceNumber: 'RDE2024121200001',
            rideId: 5,
            status: 'completed',
            createdAt: new Date('2024-12-12T10:40:00').toISOString(),
        },
        {
            driverId: 1,
            walletId: 1,
            type: 'credit',
            amount: 2500.00,
            balanceAfter: 4650.00,
            description: 'Added money via UPI',
            referenceNumber: 'TXN2024121300001',
            rideId: null,
            status: 'completed',
            createdAt: new Date('2024-12-13T08:20:00').toISOString(),
        },
        {
            driverId: 1,
            walletId: 1,
            type: 'refund',
            amount: 350.00,
            balanceAfter: 5000.00,
            description: 'Ride cancellation refund',
            referenceNumber: 'REF2024121500001',
            rideId: 6,
            status: 'completed',
            createdAt: new Date('2024-12-15T12:00:00').toISOString(),
        },

        // Driver 2 (driverId: 2, walletId: 2) - Starting balance: 0
        {
            driverId: 2,
            walletId: 2,
            type: 'credit',
            amount: 1000.00,
            balanceAfter: 1000.00,
            description: 'Added money via UPI',
            referenceNumber: 'TXN2024112000002',
            rideId: null,
            status: 'completed',
            createdAt: new Date('2024-11-20T11:00:00').toISOString(),
        },
        {
            driverId: 2,
            walletId: 2,
            type: 'ride_earning',
            amount: 180.00,
            balanceAfter: 1180.00,
            description: 'Ride earning from completed trip',
            referenceNumber: 'RDE2024120200002',
            rideId: 7,
            status: 'completed',
            createdAt: new Date('2024-12-02T15:30:00').toISOString(),
        },
        {
            driverId: 2,
            walletId: 2,
            type: 'ride_earning',
            amount: 420.00,
            balanceAfter: 1600.00,
            description: 'Ride earning from completed trip',
            referenceNumber: 'RDE2024120400002',
            rideId: 8,
            status: 'completed',
            createdAt: new Date('2024-12-04T10:15:00').toISOString(),
        },
        {
            driverId: 2,
            walletId: 2,
            type: 'ride_earning',
            amount: 380.00,
            balanceAfter: 1980.00,
            description: 'Ride earning from completed trip',
            referenceNumber: 'RDE2024120700002',
            rideId: 9,
            status: 'completed',
            createdAt: new Date('2024-12-07T14:45:00').toISOString(),
        },
        {
            driverId: 2,
            walletId: 2,
            type: 'credit',
            amount: 1000.00,
            balanceAfter: 2980.00,
            description: 'Added money via netbanking',
            referenceNumber: 'TXN2024120800002',
            rideId: null,
            status: 'completed',
            createdAt: new Date('2024-12-08T09:30:00').toISOString(),
        },
        {
            driverId: 2,
            walletId: 2,
            type: 'ride_earning',
            amount: 250.00,
            balanceAfter: 3230.00,
            description: 'Ride earning from completed trip',
            referenceNumber: 'RDE2024121000002',
            rideId: 10,
            status: 'completed',
            createdAt: new Date('2024-12-10T16:20:00').toISOString(),
        },
        {
            driverId: 2,
            walletId: 2,
            type: 'withdrawal',
            amount: 2400.00,
            balanceAfter: 830.00,
            description: 'Withdrawn to bank account',
            referenceNumber: 'WTH2024121100002',
            rideId: null,
            status: 'completed',
            createdAt: new Date('2024-12-11T14:00:00').toISOString(),
        },
        {
            driverId: 2,
            walletId: 2,
            type: 'ride_earning',
            amount: 320.00,
            balanceAfter: 1150.00,
            description: 'Ride earning from completed trip',
            referenceNumber: 'RDE2024121300002',
            rideId: 11,
            status: 'completed',
            createdAt: new Date('2024-12-13T11:50:00').toISOString(),
        },
        {
            driverId: 2,
            walletId: 2,
            type: 'credit',
            amount: 2000.00,
            balanceAfter: 3150.00,
            description: 'Added money via UPI',
            referenceNumber: 'TXN2024121400002',
            rideId: null,
            status: 'completed',
            createdAt: new Date('2024-12-14T13:15:00').toISOString(),
        },

        // Driver 3 (driverId: 3, walletId: 3) - Starting balance: 0
        {
            driverId: 3,
            walletId: 3,
            type: 'credit',
            amount: 500.00,
            balanceAfter: 500.00,
            description: 'Added money via wallet',
            referenceNumber: 'TXN2024112500003',
            rideId: null,
            status: 'completed',
            createdAt: new Date('2024-11-25T12:00:00').toISOString(),
        },
        {
            driverId: 3,
            walletId: 3,
            type: 'ride_earning',
            amount: 80.00,
            balanceAfter: 580.00,
            description: 'Ride earning from completed trip',
            referenceNumber: 'RDE2024120600003',
            rideId: 12,
            status: 'completed',
            createdAt: new Date('2024-12-06T10:30:00').toISOString(),
        },
        {
            driverId: 3,
            walletId: 3,
            type: 'ride_earning',
            amount: 120.00,
            balanceAfter: 700.00,
            description: 'Ride earning from completed trip',
            referenceNumber: 'RDE2024120900003',
            rideId: 13,
            status: 'completed',
            createdAt: new Date('2024-12-09T15:45:00').toISOString(),
        },
        {
            driverId: 3,
            walletId: 3,
            type: 'ride_earning',
            amount: 95.00,
            balanceAfter: 795.00,
            description: 'Ride earning from completed trip',
            referenceNumber: 'RDE2024121100003',
            rideId: 14,
            status: 'completed',
            createdAt: new Date('2024-12-11T09:20:00').toISOString(),
        },
        {
            driverId: 3,
            walletId: 3,
            type: 'credit',
            amount: 1000.00,
            balanceAfter: 1795.00,
            description: 'Added money via UPI',
            referenceNumber: 'TXN2024121200003',
            rideId: null,
            status: 'completed',
            createdAt: new Date('2024-12-12T14:30:00').toISOString(),
        },
        {
            driverId: 3,
            walletId: 3,
            type: 'ride_earning',
            amount: 140.00,
            balanceAfter: 1935.00,
            description: 'Ride earning from completed trip',
            referenceNumber: 'RDE2024121400003',
            rideId: 15,
            status: 'completed',
            createdAt: new Date('2024-12-14T11:10:00').toISOString(),
        },
        {
            driverId: 3,
            walletId: 3,
            type: 'withdrawal',
            amount: 1200.00,
            balanceAfter: 735.00,
            description: 'Withdrawn to bank account',
            referenceNumber: 'WTH2024121600003',
            rideId: null,
            status: 'pending',
            createdAt: new Date('2024-12-16T10:00:00').toISOString(),
        },
    ];

    await db.insert(walletTransactions).values(sampleTransactions);
    
    console.log('✅ Wallet transactions seeder completed successfully');
}

main().catch((error) => {
    console.error('❌ Seeder failed:', error);
});